spring.application.name=DaniloOrtiz

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3307/dbdaniloortiz?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}

server.address=0.0.0.0
server.port=${PORT:3001}

mercadopago.access.token=${MP_ACCESS_TOKEN:APP_USR-923627602872041-022823-3eccf7c62bce689dc48e8da8117bd389-3234523341}
app.base-url=${APP_BASE_URL:https://786b-191-205-231-62.ngrok-free.app}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sitedanilo414@gmail.com
spring.mail.password=ahqbwumaalncxivs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE